# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    working_directory: ~/projects/ingest-client
    docker:
      - image: circleci/python:3.5
        environment:
            PIPENV_VENV_IN_PROJECT: true
  
    steps:
        - checkout

        - restore_cache:  # ensure this step occurs *before* installing dependencies
            # key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            keys:
                - cache-{{ checksum "requirements.txt" }}
                - cache-
        - run: 
            name: Installing basic OS updates and libraries
            command: |
                sudo apt-get update
                # sudo apt-get install -y libjpeg-dev libtiff5-dev zlib1g-dev libfreetype6-dev liblcms2-dev libopenjpeg-dev
                uname -mrs
                sudo apt-get install -y libjpeg-dev libtiff5-dev zlib1g-dev libfreetype6-dev liblcms2-dev

        - run: 
            name: Installing tox 
            command: sudo pip install tox tox-pyenv
                
        - run:                
            name: Installing pyenv environmnents 
            command: pyenv local 2.7.10 3.4.3 3.5.1

        - run:
            name: Installing pip requirements 
            command: sudo pip install -r requirements.txt
                

        - save_cache:
            paths:
                - ~/.local
                - ~/.cache
            key: cache-{{ checksum "requirements.txt" }}

        - run:
            name: Running tests ... tox
            command: tox

