# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    working_directory: ~/ingest-client
    docker:
      - image: circleci/python:3.6.4

  
    steps:
        - checkout

        - run: mkdir test-reports

        - restore_cache:  # ensure this step occurs *before* installing dependencies
            keys:
                - cache-{{ checksum "requirements.txt" }}
                - cache-

        - run: 
            name: Installing Python requirement
            command: |
                sudo pip install -r requirements.txt
                sudo pip install -U .


        - run:
            name: Installing pip requirements in the venv
            command: |
                pip install -r requirements.txt
                
        - save_cache:
            paths:
                - ~/.local
                - ~/.cache
            key: cache-{{ checksum "requirements.txt" }}

        ####  Run Tests

        - run:
            name: Running tests ... nose2
            command: |
                cd ${CIRCLE_WORKING_DIRECTORY}
                pwd
                nose2 test

        - store_artifacts:
            path: test-reports/
            destination: tr1
        - store_test_results:
            path: test-reports/
